# Generated by Django 3.1.7 on 2021-03-30 01:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 1, 10, 47, 167983, tzinfo=utc), verbose_name='date published'),
        ),
    ]
